raft_model: raft-sintel

use_3d: False

# device/batch size for raft & geometric optical flow
device: cuda
batch_size: 12

original_fps: 30
# run once every `skip_frames` frames
skip_frames: 2

# output: 'out/ablations/min_consecutive'
output: 'out/two_objs'

raft:
  path: ${RAFT}/core/
  model: ${RAFT}/models/${RAFT_MODEL}.pth
  iters: 12

time:
  relative: true
  t0: 193
  tf: 221

img_data:
  path: ${BAG_PATH}
  topic: /hamilton/forward/color/image_raw/compressed
  camera_info_topic: /hamilton/forward/color/camera_info
  compressed: True
  
depth_data:
  path: ${BAG_PATH}
  topic: /hamilton/forward/aligned_depth_to_color/image_raw
  camera_info_topic: /hamilton/forward/aligned_depth_to_color/camera_info
  compressed: False

  depth_scale: 1000.0
  max_depth: 6.0

  # d, sigmalColor, sigmalSpace. Delete or set to null to disable.
  # bilateral_smooth_depth: [10, 100, 5] # in mm. (before scaling by 1000.0)

pose_data:
  type: bag
  path: ${BAG_PATH}
  topic: /hamilton/locus/odometry
  time_tol: 2.0
  # path: ~/Downloads/husky_gt/
  # path: ~/Downloads/husky_gt_3/
  # topic: /Husky/world
  # time_tol: 60.0

  T_odom_camera:
    input_type: "tf"
    # string: "T_FLURDF"
    parent: hamilton/base
    child: hamilton/forward_color_optical_frame

processing:
  # 3D Flows
  use_raft_flows_3d: False
  use_geometric_flows_3d: False
  use_residual_flow_3d: False
  
  # 2D Flows
  use_raft_flows_2d: True
  use_gflow_2d: True
  use_residual_2d: True
  
  # Other Data
  use_depth_data: True
  use_image_data: True

tracking:
  # for 3D:
  # if residual magnitude is greater than (min_vel_threshold + depth * vel_threshold_gain) * 1 / fps, 
  # then that point is considered dynamic
  # for 2D:
  # approximate 3d residual magnitude = depth * K^-1 * [delta_u, delta_v, 0]
  min_vel_threshold: 0.4
  vel_threshold_gain: 0.125

  # supports open, close, dilate, erode. second number is kernel size.
  post_processing: [['open', 9], ['close', 13]]

  # max axial std. deviation constraint for dynamic objects
  min_3d_std_dev: 0.05
  max_3d_std_dev: 0.5

  # maximum chamfer distance for a projected dynamic object & a newly detected
  # dynamic object to be considered for GNN association
  max_merge_dist: 1.0

  # minimum number of consecutive frames a dynamic object must be detected in 
  # for it to be considered (1 by default)
  # min_consecutive_frames: 2

viz:
  viz_video: True
  viz_dynamic_object_masks: True
  vid_dims: [1280, 960]
  viz_flag_names: ['image', 'depth', 'dynamic mask', 'raft flow', 'geometric flow', 'residual', 'orig dynamic mask']
  # must be 2D: each entry i means viz_flag_names[i] will be in the video at the location of i in the grid
  # viz_flags: [[0, 1], [3, 4]]
  viz_flags: [[0, 1], [2, 5]]
  # viz_flags: [[0, 1, 2], [3, 4, 5]]
  viz_max_residual_magnitude: 0.75
